name: suheriyatna_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  sizer: 2.0.15
  remixicon: 1.0.0
  google_fonts: 2.2.0
  intl: 0.17.0
  im_stepper: 0.1.3
  readmore: 2.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/lottie/
  uses-material-design: true

