name: suheriyatna_mobile
version: 1.5.2+9
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  sizer: 2.0.15
  remixicon: 1.0.0
  google_fonts: 2.2.0
  dio: 4.0.4
  intl: 0.17.0
  # im_stepper: 0.1.3
  readmore: 2.1.0
  # firebase_auth: 3.4.1
  firebase_core: 1.19.1
  image_picker: 0.8.4+4
  firebase_storage: 10.3.1
  flutter_phone_direct_caller: 2.1.0
  firebase_core_platform_interface: 4.5.1
  # firebase_auth_platform_interface: 6.3.1
  whatsapp_unilink: 2.0.1+1
  url_launcher: 6.1.3
  lottie: 1.2.2
  ftoast: 2.0.0
  pinput: 2.2.16 
  timer_count_down: 2.2.1
  cloud_firestore: 3.2.1
  random_string: 2.3.1
  get_storage: 2.0.3
  flutter_rounded_date_picker: 3.0.2
  dotted_border: 2.0.0+3
  clipboard: 0.1.3
  crypto: 3.0.2
  easy_pdf_viewer: 1.0.6
  fl_chart: 0.55.2
  permission_handler: 10.2.0
  excel: 2.0.1
  path_provider: 2.0.11
  lecle_downloads_path_provider: 0.0.2+8
  d_chart: 1.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  # flutter_lints: 2.0.1
  flutter_launcher_icons: 0.10.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"
  adaptive_icon_background: "#ffffff"

flutter: 
  assets: 
    - assets/images/
    - assets/lottie/
    - assets/gif/
  uses-material-design: true

